[package]
name = "wasm-unknown"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fmod-oxide = { version = "2.2.0-pre.4", path = "../../fmod-oxide" }
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]
