[package]
name = "fmod-studio-examples"
version = "1.0.0"
edition = "2024"
publish = false


[dependencies]
crossterm = "0.29.0"
fmod-oxide = { version = "*", path = "../fmod-oxide/" }
aligned-vec = "0.6.4"
